service: default
runtime: python39

env: standard
instance_class: F1
automatic_scaling:
    min_instances: 0
    max_instances: 1
    min_idle_instances: 0
    max_idle_instances: 1

entrypoint: python src/app.py